### ISSUE TITLE
#card not cliquable

### ISSUE THREAD

**Issue by madicke12** [modouaicha023/mikee.sn#2]
when i try to click on a particular card in order to watch an anime , nothing happen!!!

**Comment by modouaicha023** [comment]
Yoo @madicke12, I didn't implement it yet, I was just trying to make a quick view.
Do you wanna work on it?

**Comment by madicke12** [comment]
Of course it would be amazing to work on it

**Comment by modouaicha023** [comment]
Check out the last version, i add a manga page
